on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: test
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm install
      - run: pnpm vitest run
        env:
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.REPOSITORY_CONFIG_TESTER_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
